# Generated by Django 4.2.2 on 2023-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiants',
            fields=[
                ('matricule', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=64, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=195, verbose_name='Prenom')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
    ]
