# Generated by Django 4.2.2 on 2023-06-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'cour',
                'verbose_name_plural': 'cours',
            },
        ),
        migrations.CreateModel(
            name='cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'emploi du temps',
                'verbose_name_plural': 'emplois du temps',
            },
        ),
        migrations.CreateModel(
            name='filiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'filiaire',
                'verbose_name_plural': 'filiaire',
            },
        ),
        migrations.CreateModel(
            name='jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'jour',
                'verbose_name_plural': 'jours',
            },
        ),
        migrations.CreateModel(
            name='professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, verbose_name='nom')),
                ('prenom', models.CharField(max_length=64, verbose_name='prenom')),
            ],
            options={
                'verbose_name': 'filiaire',
                'verbose_name_plural': 'filiaire',
            },
        ),
        migrations.CreateModel(
            name='programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrd', models.IntegerField(verbose_name='heure de debut')),
                ('hrf', models.IntegerField(verbose_name='heurde fin')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.cour', verbose_name='cour')),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.emploi', verbose_name='emploi')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.jour', verbose_name='jour')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.professeur', verbose_name='professeur')),
            ],
        ),
        migrations.DeleteModel(
            name='etudiants',
        ),
        migrations.AddField(
            model_name='emploi',
            name='filiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.filiaire', verbose_name='filiaire'),
        ),
    ]
