# Generated by Django 4.2.2 on 2023-06-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0002_cour_cursus_emploi_filiaire_jour_professeur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursus',
            options={'verbose_name': 'Annee', 'verbose_name_plural': 'Annee'},
        ),
        migrations.AlterModelOptions(
            name='professeur',
            options={'verbose_name': 'professeur', 'verbose_name_plural': 'professeurs'},
        ),
        migrations.AddField(
            model_name='emploi',
            name='Annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.cursus', verbose_name='classe'),
            preserve_default=False,
        ),
    ]
