# Generated by Django 4.2.2 on 2023-06-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0003_alter_cursus_options_alter_professeur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='salle')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salle',
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='conexion.salle', verbose_name='salle'),
            preserve_default=False,
        ),
    ]
