# Generated by Django 4.2.2 on 2023-06-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0006_alter_programme_hrd_alter_programme_hrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='Annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.cursus', verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='filiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.filiaire', verbose_name='filiaire'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.cour', verbose_name='cour'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='emploi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.emploi', verbose_name='emploi'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.jour', verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.professeur', verbose_name='professeur'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexion.salle', verbose_name='salle'),
        ),
    ]
